apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      run: backend-feed
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: abdel124/udagram-api-feed
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_HOST
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_REGION         
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: JWT_SECRET 
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_PROFILE 
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name:  env-configmap
                key: AWS_BUCKET 
        ports:
        - containerPort: 80
        volumeMounts:
          - name: aws-secret
            mountPath: '/home/node/.aws'
            readOnly: true
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret