apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: abdel124/udagram-frontend:v8
        ports:
        - containerPort: 80